title: gourcetools
description: Website for all projects of GourceTools
theme: just-the-docs
color_scheme: dark

url: https://gourcetools.github.io

aux_links:
  Github: https://github.com/gourcetools/
  Tip: https://getalby.com/gourcetools

  
include:
 - .well-known/nostr.json
 - .public/img/*.*
 - .public/*
